[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_SUPABASE_URL = "YOUR_SUPABASE_URL_HERE"
  REACT_APP_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY_HERE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"